services:
  # MongoDB database service
  mongodb:
    image: mongo:7.0
    container_name: arambo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: arambo_properties
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - arambo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Express (optional UI)
  mongo-express:
    image: mongo-express:latest
    container_name: arambo-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - arambo-network

# Volumes
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

# Networks
networks:
  arambo-network:
    driver: bridge
