import { Property } from '../models/property.model';
import { connectToDatabase, disconnectFromDatabase } from '../config/connection';

const properties = [
  {
    "name": "MD. Nasirul islam( nasir)",
    "email": "mdnasirulislamnasir@example.com",
    "phone": "01738582980",
    "propertyName": "Property in DIT & Merul Badda",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1230,
    "location": "House: M 03, Merul Badda , Gulshan , Dhaka 1212 ( Beside Zaman CNG Pump)",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in DIT & Merul Badda",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-5",
    "streetAddress": "House: M 03, Merul Badda , Gulshan , Dhaka 1212 ( Beside Zaman CNG Pump)",
    "landmark": "Near main area",
    "area": "DIT & Merul Badda",
    "listingId": "RE-RENT-5",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 12,
    "totalFloor": 13,
    "yearOfConstruction": 2009,
    "rent": 30000,
    "serviceCharge": 4500,
    "advanceMonths": 2,
    "cleanHygieneScore": 8,
    "sunlightScore": 9,
    "bathroomConditionsScore": 8,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "https://i.ibb.co/5h2zqc2P/1.webp",
    "otherImages": [
      "https://i.ibb.co/fYByWSps/2.webp", 
      "https://i.ibb.co/dJKtnxrc/3.webp"
    ]
  },
  {
    "name": "MD. Nasirul islam( nasir)",
    "email": "mdnasirulislamnasir@example.com",
    "phone": "01738582980",
    "propertyName": "Property in DIT & Merul Badda",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1160,
    "location": "House: M 03, Merul badda , gulshan , dhaka 1212 ( Beside Zaman Cng Pump)",
    "bedrooms": 3,
    "bathroom": 2,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in DIT & Merul Badda",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-6",
    "streetAddress": "House: M 03, Merul badda , gulshan , dhaka 1212 ( Beside Zaman Cng Pump)",
    "landmark": "Near main area",
    "area": "DIT & Merul Badda",
    "listingId": "RE-RENT-6",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 8,
    "totalFloor": 13,
    "yearOfConstruction": 2009,
    "rent": 30000,
    "serviceCharge": 4500,
    "advanceMonths": 2,
    "cleanHygieneScore": 8,
    "sunlightScore": 9,
    "bathroomConditionsScore": 8,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 3",
    "email": "propertyowner3@example.com",
    "phone": "01779307513",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1460,
    "location": "14/2 C, Road3/A, Dhanmondi Jigatola",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-7",
    "streetAddress": "14/2 C, Road3/A, Dhanmondi Jigatola",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-7",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 1,
    "totalFloor": 6,
    "yearOfConstruction": 2008,
    "rent": 32000,
    "serviceCharge": 6000,
    "advanceMonths": 2,
    "cleanHygieneScore": 7,
    "sunlightScore": 8,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 4",
    "email": "propertyowner4@example.com",
    "phone": "01332513282",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1650,
    "location": "House 11/1, Road 4/A Jigatola",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-8",
    "streetAddress": "House 11/1, Road 4/A Jigatola",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-8",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 9,
    "yearOfConstruction": 2010,
    "rent": 40000,
    "serviceCharge": 6000,
    "advanceMonths": 2,
    "cleanHygieneScore": 5,
    "sunlightScore": 8,
    "bathroomConditionsScore": 6,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 5",
    "email": "propertyowner5@example.com",
    "phone": "01789950401",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 41/22-A jigatola Haji afsarudddin road",
    "bedrooms": 1,
    "bathroom": 1,
    "baranda": 0,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-9",
    "streetAddress": "House 41/22-A jigatola Haji afsarudddin road",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-9",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Bachelor",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 1,
    "totalFloor": 4,
    "yearOfConstruction": 2020,
    "rent": 10000,
    "serviceCharge": 1050,
    "advanceMonths": 1,
    "cleanHygieneScore": 3,
    "sunlightScore": 1,
    "bathroomConditionsScore": 4,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 6",
    "email": "propertyowner6@example.com",
    "phone": "01750974530",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "Munshibari road puran kachabajar",
    "bedrooms": 1,
    "bathroom": 1,
    "baranda": 1,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-10",
    "streetAddress": "Munshibari road puran kachabajar",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-10",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Bachelor",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 6,
    "yearOfConstruction": 2013,
    "rent": 6000,
    "serviceCharge": 2000,
    "advanceMonths": 1,
    "cleanHygieneScore": 6,
    "sunlightScore": 7,
    "bathroomConditionsScore": 6,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 7",
    "email": "propertyowner7@example.com",
    "phone": "1719785888",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 41/23/10 jigatola new road",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-11",
    "streetAddress": "House 41/23/10 jigatola new road",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-11",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 5,
    "totalFloor": 6,
    "yearOfConstruction": 2015,
    "rent": 27000,
    "serviceCharge": 2000,
    "advanceMonths": 2,
    "cleanHygieneScore": 5,
    "sunlightScore": 7,
    "bathroomConditionsScore": 4,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 8",
    "email": "propertyowner8@example.com",
    "phone": "01996813630",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1580,
    "location": "House 209 ,road10/A modhubazar dhanmondi",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-12",
    "streetAddress": "House 209 ,road10/A modhubazar dhanmondi",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-12",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 6,
    "yearOfConstruction": 2008,
    "rent": 32000,
    "serviceCharge": 6500,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 7,
    "bathroomConditionsScore": 8,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Nazmul Abedin",
    "email": "nazmulabedin@example.com",
    "phone": "01819222138",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1600,
    "location": "House 127/A road 9/A dhanmondi R/A",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-13",
    "streetAddress": "House 127/A road 9/A dhanmondi R/A",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-13",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 7,
    "yearOfConstruction": 2011,
    "rent": 33000,
    "serviceCharge": 7000,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 9,
    "bathroomConditionsScore": 8,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": true,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": true,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 10",
    "email": "propertyowner10@example.com",
    "phone": "01975378894",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "Dhanmondi jigatola notun rasta",
    "bedrooms": 1,
    "bathroom": 1,
    "baranda": 1,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-14",
    "streetAddress": "Dhanmondi jigatola notun rasta",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-14",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Bachelor",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 4,
    "totalFloor": 6,
    "yearOfConstruction": 2012,
    "rent": 7000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 5,
    "sunlightScore": 5,
    "bathroomConditionsScore": 4,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 11",
    "email": "propertyowner11@example.com",
    "phone": "01776190669",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 12, road 4, block A , Banasree",
    "bedrooms": 1,
    "bathroom": 2,
    "baranda": 1,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-15",
    "streetAddress": "House 12, road 4, block A , Banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-15",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 7,
    "yearOfConstruction": 2016,
    "rent": 13500,
    "serviceCharge": 2500,
    "advanceMonths": 1,
    "cleanHygieneScore": 6,
    "sunlightScore": 7,
    "bathroomConditionsScore": 5,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 12",
    "email": "propertyowner12@example.com",
    "phone": "1736348138",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 18 road 2 block A Banasree",
    "bedrooms": 2,
    "bathroom": 1,
    "baranda": 1,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-16",
    "streetAddress": "House 18 road 2 block A Banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-16",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 1,
    "totalFloor": 6,
    "yearOfConstruction": 2012,
    "rent": 14000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 6,
    "sunlightScore": 2,
    "bathroomConditionsScore": 5,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Falu Mia",
    "email": "falumia@example.com",
    "phone": "01990240293",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 22, road 2 bloack A banasree",
    "bedrooms": 2,
    "bathroom": 2,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-17",
    "streetAddress": "House 22, road 2 bloack A banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-17",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 6,
    "yearOfConstruction": 2015,
    "rent": 22000,
    "serviceCharge": 4000,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 8,
    "bathroomConditionsScore": 8,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 14",
    "email": "propertyowner14@example.com",
    "phone": "01975248536",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 24, road 1 block B banasree",
    "bedrooms": 2,
    "bathroom": 2,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-18",
    "streetAddress": "House 24, road 1 block B banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-18",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 7,
    "yearOfConstruction": 2021,
    "rent": 14000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 5,
    "sunlightScore": 6,
    "bathroomConditionsScore": 4,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 15",
    "email": "propertyowner15@example.com",
    "phone": "1716400333",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 14 road 2 , Black B banasree",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 1,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-19",
    "streetAddress": "House 14 road 2 , Black B banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-19",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 1,
    "totalFloor": 5,
    "yearOfConstruction": 2017,
    "rent": 17000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 2,
    "bathroomConditionsScore": 7,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 16",
    "email": "propertyowner16@example.com",
    "phone": "01624726950",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 960,
    "location": "House 23, road 5 , Block F Banasree",
    "bedrooms": 2,
    "bathroom": 2,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-20",
    "streetAddress": "House 23, road 5 , Block F Banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-20",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 5,
    "totalFloor": 6,
    "yearOfConstruction": 2011,
    "rent": 16000,
    "serviceCharge": 100,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 8,
    "bathroomConditionsScore": 6,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 17",
    "email": "propertyowner17@example.com",
    "phone": "01819078453",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "Banasree E block  road 1",
    "bedrooms": 2,
    "bathroom": 1,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-21",
    "streetAddress": "Banasree E block  road 1",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-21",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 8,
    "totalFloor": 8,
    "yearOfConstruction": 2009,
    "rent": 18000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 9,
    "bathroomConditionsScore": 6,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 18",
    "email": "propertyowner18@example.com",
    "phone": "01712477608",
    "propertyName": "Property in Mirpur DOHs",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 03, road 07, Block C , sector 06 Mirpur",
    "bedrooms": 3,
    "bathroom": 4,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Mirpur DOHs",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-22",
    "streetAddress": "House 03, road 07, Block C , sector 06 Mirpur",
    "landmark": "Near main area",
    "area": "Mirpur DOHs",
    "listingId": "RE-RENT-22",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 7,
    "totalFloor": 12,
    "yearOfConstruction": 2013,
    "rent": 40000,
    "serviceCharge": 1080,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 9,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 19",
    "email": "propertyowner19@example.com",
    "phone": "01796961707",
    "propertyName": "Property in Aftabnagar",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 14, road 08, block E , sector 3 , aftabnagar",
    "bedrooms": 2,
    "bathroom": 2,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Aftabnagar",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-23",
    "streetAddress": "House 14, road 08, block E , sector 3 , aftabnagar",
    "landmark": "Near main area",
    "area": "Aftabnagar",
    "listingId": "RE-RENT-23",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 10,
    "totalFloor": 11,
    "yearOfConstruction": 2001,
    "rent": 20000,
    "serviceCharge": 3000,
    "advanceMonths": 1,
    "cleanHygieneScore": 10,
    "sunlightScore": 9,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 20",
    "email": "propertyowner20@example.com",
    "phone": "01755557774",
    "propertyName": "Property in Aftabnagar",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 16, road 2, D block , sector 2 , aftabnagar",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Aftabnagar",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-24",
    "streetAddress": "House 16, road 2, D block , sector 2 , aftabnagar",
    "landmark": "Near main area",
    "area": "Aftabnagar",
    "listingId": "RE-RENT-24",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 4,
    "totalFloor": 7,
    "yearOfConstruction": 2001,
    "rent": 23000,
    "serviceCharge": 4000,
    "advanceMonths": 1,
    "cleanHygieneScore": 10,
    "sunlightScore": 9,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": true,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 21",
    "email": "propertyowner21@example.com",
    "phone": "01913933188",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 13, Road 1, block G Banasree",
    "bedrooms": 2,
    "bathroom": 2,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-25",
    "streetAddress": "House 13, Road 1, block G Banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-25",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 7,
    "yearOfConstruction": 2016,
    "rent": 15000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 6,
    "sunlightScore": 7,
    "bathroomConditionsScore": 5,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 22",
    "email": "propertyowner22@example.com",
    "phone": "01321855005",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 2, road 2, G block , banasree",
    "bedrooms": 4,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-26",
    "streetAddress": "House 2, road 2, G block , banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-26",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 13,
    "yearOfConstruction": 2010,
    "rent": 30000,
    "serviceCharge": 5500,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 8,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 23",
    "email": "propertyowner23@example.com",
    "phone": "01709301153",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 32, road 5, F block , Banasree",
    "bedrooms": 4,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-27",
    "streetAddress": "House 32, road 5, F block , Banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-27",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 5,
    "yearOfConstruction": 2020,
    "rent": 27000,
    "serviceCharge": 5000,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 8,
    "bathroomConditionsScore": 6,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 24",
    "email": "propertyowner24@example.com",
    "phone": "01860606195",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 13, road 4, block F banasree",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-29",
    "streetAddress": "House 13, road 4, block F banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-29",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 6,
    "yearOfConstruction": 2001,
    "rent": 22000,
    "serviceCharge": 3000,
    "advanceMonths": 1,
    "cleanHygieneScore": 10,
    "sunlightScore": 9,
    "bathroomConditionsScore": 10,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "A.K.M Kuddusur Rahman",
    "email": "akmkuddusurrahman@example.com",
    "phone": "01884693715",
    "propertyName": "Property in Banasree",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 4, road 2, block F Banasree",
    "bedrooms": 3,
    "bathroom": 2,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Banasree",
    "firstOwner": false,
    "lift": false,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-30",
    "streetAddress": "House 4, road 2, block F Banasree",
    "landmark": "Near main area",
    "area": "Banasree",
    "listingId": "RE-RENT-30",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 4,
    "yearOfConstruction": 2013,
    "rent": 22000,
    "serviceCharge": 1000,
    "advanceMonths": 1,
    "cleanHygieneScore": 6,
    "sunlightScore": 8,
    "bathroomConditionsScore": 9,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 26",
    "email": "propertyowner26@example.com",
    "phone": "01915903899",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 4, road 6, block A, kaderabad",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-31",
    "streetAddress": "House 4, road 6, block A, kaderabad",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-31",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 5,
    "totalFloor": 7,
    "yearOfConstruction": 2014,
    "rent": 20000,
    "serviceCharge": 4000,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 7,
    "bathroomConditionsScore": 5,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 27",
    "email": "propertyowner27@example.com",
    "phone": "017 2754 7520",
    "propertyName": "Property in Bashundhara Residential",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 118, road 7 , D block Banshundhara",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Bashundhara Residential",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-32",
    "streetAddress": "House 118, road 7 , D block Banshundhara",
    "landmark": "Near main area",
    "area": "Bashundhara Residential",
    "listingId": "RE-RENT-32",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 7,
    "yearOfConstruction": 2008,
    "rent": 38000,
    "serviceCharge": 8000,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 9,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 28",
    "email": "propertyowner28@example.com",
    "phone": "01729253861",
    "propertyName": "Property in Bashundhara Residential",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 103, road 06, block D Bashundhara",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Bashundhara Residential",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-33",
    "streetAddress": "House 103, road 06, block D Bashundhara",
    "landmark": "Near main area",
    "area": "Bashundhara Residential",
    "listingId": "RE-RENT-33",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 7,
    "yearOfConstruction": 2007,
    "rent": 47000,
    "serviceCharge": 7000,
    "advanceMonths": 2,
    "cleanHygieneScore": 8,
    "sunlightScore": 9,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 29",
    "email": "propertyowner29@example.com",
    "phone": "01711432196",
    "propertyName": "Property in Bashundhara Residential",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 57/C, road 04, block D bashundhara",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Bashundhara Residential",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-34",
    "streetAddress": "House 57/C, road 04, block D bashundhara",
    "landmark": "Near main area",
    "area": "Bashundhara Residential",
    "listingId": "RE-RENT-34",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 9,
    "yearOfConstruction": 2010,
    "rent": 50000,
    "serviceCharge": 0,
    "advanceMonths": 2,
    "cleanHygieneScore": 7,
    "sunlightScore": 6,
    "bathroomConditionsScore": 6,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 30",
    "email": "propertyowner30@example.com",
    "phone": "1727512806",
    "propertyName": "Property in Bashundhara Residential",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 494, Abdur sadeq road , block F Bashundhara",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Bashundhara Residential",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-35",
    "streetAddress": "House 494, Abdur sadeq road , block F Bashundhara",
    "landmark": "Near main area",
    "area": "Bashundhara Residential",
    "listingId": "RE-RENT-35",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 6,
    "yearOfConstruction": 2009,
    "rent": 42000,
    "serviceCharge": 5500,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 7,
    "bathroomConditionsScore": 8,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 31",
    "email": "propertyowner31@example.com",
    "phone": "01711129347",
    "propertyName": "Property in Bashundhara Residential",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 269, road 13, block C Bashundhara",
    "bedrooms": 3,
    "bathroom": 4,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Bashundhara Residential",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-36",
    "streetAddress": "House 269, road 13, block C Bashundhara",
    "landmark": "Near main area",
    "area": "Bashundhara Residential",
    "listingId": "RE-RENT-36",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 8,
    "yearOfConstruction": 2009,
    "rent": 40000,
    "serviceCharge": 5000,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 8,
    "bathroomConditionsScore": 6,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 32",
    "email": "propertyowner32@example.com",
    "phone": "01643197086",
    "propertyName": "Property in Dhanmondi",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 08, road 5, Dhanmondi",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 1,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Dhanmondi",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-37",
    "streetAddress": "House 08, road 5, Dhanmondi",
    "landmark": "Near main area",
    "area": "Dhanmondi",
    "listingId": "RE-RENT-37",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 14,
    "yearOfConstruction": 2010,
    "rent": 65000,
    "serviceCharge": 0,
    "advanceMonths": 2,
    "cleanHygieneScore": 9,
    "sunlightScore": 7,
    "bathroomConditionsScore": 9,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 33",
    "email": "propertyowner33@example.com",
    "phone": "01822931538",
    "propertyName": "Property in Uttara Sector 13",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 15, road 15, sector 13 Uttara",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Uttara Sector 13",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-38",
    "streetAddress": "House 15, road 15, sector 13 Uttara",
    "landmark": "Near main area",
    "area": "Uttara Sector 13",
    "listingId": "RE-RENT-38",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 4,
    "totalFloor": 7,
    "yearOfConstruction": 2013,
    "rent": 80000,
    "serviceCharge": 6000,
    "advanceMonths": 2,
    "cleanHygieneScore": 8,
    "sunlightScore": 8,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Sakib Khan",
    "email": "sakibkhan@example.com",
    "phone": "01915933991",
    "propertyName": "Property in Niketan",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 2800,
    "location": "House 1, Road 6, Block E, Niketon",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Niketan",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-39",
    "streetAddress": "House 1, Road 6, Block E, Niketon",
    "landmark": "Near main area",
    "area": "Niketan",
    "listingId": "RE-RENT-39",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 9,
    "yearOfConstruction": 2025,
    "rent": 100000,
    "serviceCharge": 10000,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 35",
    "email": "propertyowner35@example.com",
    "phone": "01924379500",
    "propertyName": "Property in Niketan",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1800,
    "location": "House 135, Road 3, Block A, Niketon",
    "bedrooms": 3,
    "bathroom": 4,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Niketan",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-40",
    "streetAddress": "House 135, Road 3, Block A, Niketon",
    "landmark": "Near main area",
    "area": "Niketan",
    "listingId": "RE-RENT-40",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 5,
    "totalFloor": 6,
    "yearOfConstruction": 2016,
    "rent": 60000,
    "serviceCharge": 6500,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 7,
    "bathroomConditionsScore": 7,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 36",
    "email": "propertyowner36@example.com",
    "phone": "01951520057",
    "propertyName": "Property in Niketan",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1680,
    "location": "House 141, Road 3, Block A, Niketon",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Niketan",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-41",
    "streetAddress": "House 141, Road 3, Block A, Niketon",
    "landmark": "Near main area",
    "area": "Niketan",
    "listingId": "RE-RENT-41",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 6,
    "yearOfConstruction": 2014,
    "rent": 36000,
    "serviceCharge": 65000,
    "advanceMonths": 1,
    "cleanHygieneScore": 7,
    "sunlightScore": 7,
    "bathroomConditionsScore": 6,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 37",
    "email": "propertyowner37@example.com",
    "phone": "01952595002",
    "propertyName": "Property in Niketan",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1,
    "location": "House 13/15, Road 1,, block B, Niketon",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Niketan",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-42",
    "streetAddress": "House 13/15, Road 1,, block B, Niketon",
    "landmark": "Near main area",
    "area": "Niketan",
    "listingId": "RE-RENT-42",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 4,
    "totalFloor": 6,
    "yearOfConstruction": 2017,
    "rent": 50000,
    "serviceCharge": 6000,
    "advanceMonths": 1,
    "cleanHygieneScore": 8,
    "sunlightScore": 6,
    "bathroomConditionsScore": 7,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Dulal",
    "email": "dulal@example.com",
    "phone": "01936587040",
    "propertyName": "Property in Gudaraghat",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1500,
    "location": "MF Village,, House TA-160/3/D, Moddho Badda link Road",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gudaraghat",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-43",
    "streetAddress": "MF Village,, House TA-160/3/D, Moddho Badda link Road",
    "landmark": "Near main area",
    "area": "Gudaraghat",
    "listingId": "RE-RENT-43",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 2,
    "totalFloor": 7,
    "yearOfConstruction": 2011,
    "rent": 30000,
    "serviceCharge": 0,
    "advanceMonths": 1,
    "cleanHygieneScore": 6,
    "sunlightScore": 5,
    "bathroomConditionsScore": 6,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 39",
    "email": "propertyowner39@example.com",
    "phone": "01937081872",
    "propertyName": "Property in Gudaraghat",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1800,
    "location": "Lake Garden,, House TA-171, Moddho Badda Link Road Beside Lake",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gudaraghat",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-44",
    "streetAddress": "Lake Garden,, House TA-171, Moddho Badda Link Road Beside Lake",
    "landmark": "Near main area",
    "area": "Gudaraghat",
    "listingId": "RE-RENT-44",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 5,
    "totalFloor": 9,
    "yearOfConstruction": 2017,
    "rent": 35000,
    "serviceCharge": 5000,
    "advanceMonths": 2,
    "cleanHygieneScore": 8,
    "sunlightScore": 8,
    "bathroomConditionsScore": 7,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 40",
    "email": "propertyowner40@example.com",
    "phone": "10716656443",
    "propertyName": "Property in South Badda",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1550,
    "location": "Rubi Amena Lake View, House TA-203 South Badda",
    "bedrooms": 3,
    "bathroom": 4,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in South Badda",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-45",
    "streetAddress": "Rubi Amena Lake View, House TA-203 South Badda",
    "landmark": "Near main area",
    "area": "South Badda",
    "listingId": "RE-RENT-45",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 7,
    "yearOfConstruction": 2015,
    "rent": 35000,
    "serviceCharge": 3000,
    "advanceMonths": 2,
    "cleanHygieneScore": 7,
    "sunlightScore": 7,
    "bathroomConditionsScore": 6,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": true,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 41",
    "email": "propertyowner41@example.com",
    "phone": "01716495515",
    "propertyName": "Property in South Badda",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1500,
    "location": "Farhad Lake View, PA-149/4,149/6, South Badda Lake View",
    "bedrooms": 3,
    "bathroom": 3,
    "baranda": 2,
    "category": "Unfurnished",
    "notes": "Property with good amenities in South Badda",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-46",
    "streetAddress": "Farhad Lake View, PA-149/4,149/6, South Badda Lake View",
    "landmark": "Near main area",
    "area": "South Badda",
    "listingId": "RE-RENT-46",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 8,
    "yearOfConstruction": 2025,
    "rent": 45000,
    "serviceCharge": 4000,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 8,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Property Owner 42",
    "email": "propertyowner42@example.com",
    "phone": "01829282674",
    "propertyName": "Property in Middle Badda",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 1900,
    "location": "Samin nurunnessa villa, House Ga-74, Link Road Moddho Badda",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Middle Badda",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-47",
    "streetAddress": "Samin nurunnessa villa, House Ga-74, Link Road Moddho Badda",
    "landmark": "Near main area",
    "area": "Middle Badda",
    "listingId": "RE-RENT-47",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 7,
    "yearOfConstruction": 2015,
    "rent": 40000,
    "serviceCharge": 6000,
    "advanceMonths": 2,
    "cleanHygieneScore": 7,
    "sunlightScore": 8,
    "bathroomConditionsScore": 7,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 2",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 4500,
    "location": "Gulshan 2",
    "bedrooms": 4,
    "bathroom": 5,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 2",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-48",
    "streetAddress": "Gulshan 2",
    "landmark": "Near main area",
    "area": "Gulshan 2",
    "listingId": "RE-RENT-48",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 1,
    "yearOfConstruction": 2024,
    "rent": 320000,
    "serviceCharge": 0,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": true,
    "gym": true,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 2",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 5200,
    "location": "Gulshan 2",
    "bedrooms": 4,
    "bathroom": 5,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 2",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-49",
    "streetAddress": "Gulshan 2",
    "landmark": "Near main area",
    "area": "Gulshan 2",
    "listingId": "RE-RENT-49",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 1,
    "yearOfConstruction": 2023,
    "rent": 300000,
    "serviceCharge": 20000,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": true,
    "gym": true,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 2",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 4500,
    "location": "Gulshan 2",
    "bedrooms": 4,
    "bathroom": 5,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 2",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-50",
    "streetAddress": "Gulshan 2",
    "landmark": "Near main area",
    "area": "Gulshan 2",
    "listingId": "RE-RENT-50",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 1,
    "yearOfConstruction": 2023,
    "rent": 320000,
    "serviceCharge": 0,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": true,
    "gym": true,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 2",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 3500,
    "location": "Gulshan",
    "bedrooms": 4,
    "bathroom": 5,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 2",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-51",
    "streetAddress": "Gulshan",
    "landmark": "Near main area",
    "area": "Gulshan 2",
    "listingId": "RE-RENT-51",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 4,
    "totalFloor": 1,
    "yearOfConstruction": 2025,
    "rent": 350000,
    "serviceCharge": 0,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 1",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 3721,
    "location": "Gulshan",
    "bedrooms": 4,
    "bathroom": 5,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 1",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-52",
    "streetAddress": "Gulshan",
    "landmark": "Near main area",
    "area": "Gulshan 1",
    "listingId": "RE-RENT-52",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 13,
    "totalFloor": 15,
    "yearOfConstruction": 2023,
    "rent": 250000,
    "serviceCharge": 15000,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": true,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 1",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 3721,
    "location": "Gulshan",
    "bedrooms": 4,
    "bathroom": 5,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 1",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-53",
    "streetAddress": "Gulshan",
    "landmark": "Near main area",
    "area": "Gulshan 1",
    "listingId": "RE-RENT-53",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 6,
    "totalFloor": 13,
    "yearOfConstruction": 2023,
    "rent": 250000,
    "serviceCharge": 15000,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": true,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 1",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 3000,
    "location": "Gulshan",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 3,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 1",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-54",
    "streetAddress": "Gulshan",
    "landmark": "Near main area",
    "area": "Gulshan 1",
    "listingId": "RE-RENT-54",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 9,
    "totalFloor": 1,
    "yearOfConstruction": 2023,
    "rent": 160000,
    "serviceCharge": 13000,
    "advanceMonths": 2,
    "cleanHygieneScore": 10,
    "sunlightScore": 10,
    "bathroomConditionsScore": 10,
    "cctv": true,
    "communityHall": true,
    "gym": true,
    "masjid": false,
    "parking": true,
    "petsAllowed": true,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  },
  {
    "name": "Imran",
    "email": "imran@example.com",
    "phone": "01910064138",
    "propertyName": "Property in Gulshan 2",
    "listingType": "For Rent",
    "propertyType": "House",
    "size": 3000,
    "location": "Road 36, Gulshan 2, Azad Mosque Side",
    "bedrooms": 4,
    "bathroom": 4,
    "baranda": 4,
    "category": "Unfurnished",
    "notes": "Property with good amenities in Gulshan 2",
    "firstOwner": false,
    "lift": true,
    "isConfirmed": true,
    "paperworkUpdated": true,
    "onLoan": false,
    "houseId": "RE-RENT-55",
    "streetAddress": "Road 36, Gulshan 2, Azad Mosque Side",
    "landmark": "Near main area",
    "area": "Gulshan 2",
    "listingId": "RE-RENT-55",
    "inventoryStatus": "Looking for Rent",
    "tenantType": "Family",
    "propertyCategory": "Residential",
    "furnishingStatus": "Non-Furnished",
    "availableFrom": "2025-08-01T00:00:00.000Z",
    "floor": 3,
    "totalFloor": 9,
    "yearOfConstruction": 2019,
    "rent": 130000,
    "serviceCharge": 0,
    "advanceMonths": 2,
    "cleanHygieneScore": 9,
    "sunlightScore": 9,
    "bathroomConditionsScore": 9,
    "cctv": false,
    "communityHall": false,
    "gym": false,
    "masjid": false,
    "parking": false,
    "petsAllowed": false,
    "swimmingPool": false,
    "trainedGuard": false,
    "coverImage": "",
    "otherImages": []
  }
];

export async function seedProperties(): Promise<void> {
  try {
    console.log('Starting property seeding with real CSV data (updated enums)...');
    
    await connectToDatabase();
    
    await Property.deleteMany({});
    console.log('Cleared existing properties');
    
    const createdProperties = await Property.insertMany(properties);
    console.log(`Seeded ${createdProperties.length} properties successfully`);
    
    console.log('Property seeding summary:');
    console.log(`   - Total properties: ${createdProperties.length}`);
    
    const areaGroups = createdProperties.reduce((groups: any, property: any) => {
      const area = property.area || 'No Area';
      groups[area] = (groups[area] || 0) + 1;
      return groups;
    }, {});
    
    console.log('Properties by area (all areas now match CSV exactly):');
    Object.entries(areaGroups).forEach(([area, count]) => {
      console.log(`   - ${area}: ${count}`);
    });
    
    const rents = createdProperties.map((p: any) => p.rent).filter((r: number) => r > 0);
    if (rents.length > 0) {
      const minRent = Math.min(...rents);
      const maxRent = Math.max(...rents);
      const avgRent = Math.round(rents.reduce((sum: number, r: number) => sum + r, 0) / rents.length);
      
      console.log('Rent analysis:');
      console.log(`   - Min rent: TK${minRent.toLocaleString()}`);
      console.log(`   - Max rent: TK${maxRent.toLocaleString()}`);
      console.log(`   - Avg rent: TK${avgRent.toLocaleString()}`);
    }
    
  } catch (error) {
    console.error('Error seeding properties:', error);
    throw error;
  } finally {
    await disconnectFromDatabase();
  }
}

if (require.main === module) {
  seedProperties()
    .then(() => {
      console.log('Property seeding completed successfully with CSV-matched enums');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Property seeding failed:', error);
      process.exit(1);
    });
}